export const locators = {
    searchJobInput: 'input[placeholder="Title, skill or Company"]',
    selectedJob: 'jobs-search__job-details',
    jobDetailTopCard: '//div[contains(@class, "job-details-jobs-unified-top-card__container")]',
    applyButton: '#jobs-apply-button-id',
    emailLabel: '//span[text()="Email"]/ancestor::div[1]',
    phoneCountryCodeLabel: '//span[text()="Phone country code"]',
    phoneLabel: '//span[text()="Phone"]',
    resumeUploadButton: '//span[aria-label*="Upload resume"]',
    submitApplicationButton: 'button[aria-label="Submit application"]',
    applyJobDialog: 'div[role="dialog"]',
    endLineButton: '//footer[@role="presentation"]//button',
    searchResultJobCards: '//div[@id="jobs-search-results-footer"]/preceding-sibling::ul',
    uploadResumeInput: '[id*="jobs-document-upload-file-input-upload-resume"]',
    reviewApplicationButton: 'button[aria-label="Review your application"]',
    submitApplication: 'button[aria-label="Submit application"]',
    uploadedFileName: '//span[text()="Be sure to include an updated resume"]/following-sibling::div//h3',
    nextButton: 'Next',
    easyApplyFilter: '#searchFilter_applyWithLinkedin',
    requireresumeMessage: '//span[text()="A resume is required"]',
    invalidResumeMessage: '//div[@class="jobs-document-upload-redesign-card__error"]//span/span',
    removeDocument: 'Clear document',
}